# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='car_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
