# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_time', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Spots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spots', models.CharField(max_length=50)),
                ('lat', models.CharField(max_length=50)),
                ('lang', models.CharField(max_length=50)),
                ('radius', models.CharField(max_length=50)),
                ('timer', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='paking',
            name='paking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paking.Spots'),
        ),
    ]
