# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paking', '0002_remove_spots_radius'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paking',
            old_name='paking',
            new_name='parking',
        ),
    ]
