# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paking', '0003_auto_20170410_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paking',
            name='parking',
        ),
        migrations.RemoveField(
            model_name='paking',
            name='parking_time',
        ),
        migrations.RemoveField(
            model_name='spots',
            name='timer',
        ),
        migrations.AddField(
            model_name='paking',
            name='availality',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paking',
            name='paking',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spots',
            name='parkingtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
